name: Checkstyle

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkstyle for Java
        uses: dbelyaev/action-checkstyle@v1.7.0
        with:
          github_token: ${{ github.token }}
          reporter: github-pr-check
          level: warning
